# Generated by Django 5.2.10 on 2026-02-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_student_face_encoding_remove_student_roll_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceencoding',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='faceencoding',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
